### ISSUE TITLE
segfault in debugger -- object with non-malloc-ed drv->name

### ISSUE THREAD

**Issue by charlesdaniels** [JulNadeauCA/libagar#15]
Relevant GDB session:

```
Thread 1 "graph_editor" hit Breakpoint 1, WidgetSelected (event=0x7fffffffd5c0) at debugger.c:334
334                             AG_LabelNewPolled(nTab, AG_LABEL_HFILL, _("Cursor driver: %s"),
(gdb) p wid
$1 = (AG_Widget *) 0x555555786f70
(gdb) p wid->drv
$2 = (struct ag_driver *) 0x100000001
(gdb) p drv
$3 = (AG_Driver *) 0x100000001
(gdb) p drv->name
There is no member named name.
(gdb) p ((struct ag_object*)(drv))
$4 = (struct ag_object *) 0x100000001
(gdb) p ((struct ag_object*)(drv))->name
Cannot access memory at address 0x100000001
(gdb)
```

And the back-trace

```
Thread 1 "graph_editor" received signal SIGSEGV, Segmentation fault.
0x00007ffff7876115 in AG_Strlcpy (dst=0x5555561ad56f "",
    src=0x100000002 <error: Cannot access memory at address 0x100000002>, dsize=112) at string.c:733
733                             if ((*dst++ = *src++) == '\0')
(gdb) bt
#0  0x00007ffff7876115 in AG_Strlcpy (dst=0x5555561ad56f "",
    src=0x100000002 <error: Cannot access memory at address 0x100000002>, dsize=112) at string.c:733
#1  0x00007ffff78759ce in AG_ProcessFmtString (fs=0x5555557b6e00, dst=0x5555561ad560 "Cursor driver: ", dstSize=128)
    at string.c:325
#2  0x00007ffff7afcf98 in DrawPolled (lbl=0x5555560ebda0) at label.c:403
#3  0x00007ffff7afca31 in Draw (obj=0x5555560ebda0) at label.c:484
#4  0x00007ffff7adee51 in AG_WidgetDraw (p=0x5555560ebda0) at widget.c:1329
#5  0x00007ffff7afaf4a in Draw (obj=0x5555560e97a0) at box.c:195
#6  0x00007ffff7ae0043 in AG_WidgetInheritDraw (obj=0x5555560e97a0) at widget.c:1723
#7  0x00007ffff7adee51 in AG_WidgetDraw (p=0x5555560e97a0) at widget.c:1329
#8  0x00007ffff7b35d8a in Draw (obj=0x55555607c730) at notebook.c:134
#9  0x00007ffff7adee51 in AG_WidgetDraw (p=0x55555607c730) at widget.c:1329
#10 0x00007ffff7afaf4a in Draw (obj=0x555555df8280) at box.c:195
#11 0x00007ffff7adee51 in AG_WidgetDraw (p=0x555555df8280) at widget.c:1329
#12 0x00007ffff7b58af4 in Draw (obj=0x555555df2fd0) at pane.c:343
#13 0x00007ffff7adee51 in AG_WidgetDraw (p=0x555555df2fd0) at widget.c:1329
#14 0x00007ffff7ae73d9 in Draw (obj=0x555555deee20) at window.c:630
#15 0x00007ffff7adee51 in AG_WidgetDraw (p=0x555555deee20) at widget.c:1329
#16 0x00007ffff7ad1772 in GLX_RenderWindow (win=0x555555deee20) at drv_glx.c:870
#17 0x00007ffff7ae34db in AG_WindowDrawQueued () at window.c:967
#18 0x00007ffff7ad45fa in GLX_EventEpilogue (es=0x55555576cac0, event=0x55555576cae0) at drv_glx.c:2079
#19 0x00007ffff7869d4f in AG_EventLoop () at event.c:1631
#20 0x000055555555642b in main (argc=1, argv=0x7fffffffe6b8) at main.c:378
```

See attached screenshot -- I had just clicked on the "cursors" tab. I'm not sure I know enough about Agar's internals to debug this further. [This](https://github.com/charlesdaniels/teaching-learning/blob/master/libraries/libagar/graph_editor/main.c) is the application I was using to test with.

![screenshot_2019-06-07_at_16_31_26](https://user-images.githubusercontent.com/11738895/59131925-c3100f80-8941-11e9-93e5-ee99392b883f.png)

**Comment by JulNadeauCA** [comment]
This should be fixed as of r10694.
